-- test (INITIAL) --

CREATE TABLE test (
	id INT(11) NOT NULL  COMMENT 'ID for person',
	name VARCHAR(50) NOT NULL COMMENT 'name of person'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT * FROM test;
TRUNCATE test;
DROP TABLE IF EXISTS test;